version: "2"
services:
  db:
    image: postgres:9
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - gbuy
    restart: always
  web:
    build: .
    env_file: .env
    environment:
      DATABASE_USER: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: db
    depends_on:
      - db
    networks:
      - gbuy
      - nginx
    restart: always
    expose:
      - 3000
  delayed_job:
    build: .
    env_file: .env
    environment:
      DATABASE_USER: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: db
    depends_on:
      - db
    networks:
      - gbuy
    restart: always
    command: [bin/delayed_job, run]
volumes:
  postgres: {}
networks:
  gbuy: {}
  nginx:
    external: true
